name: Python Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List repository content
      run: ls -la

    - name: Setup Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Create virtual environment
      run: python -m venv venv

    - name: Activate virtual environment
      run: source ./venv/bin/activate

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
      continue-on-error: true

    - name: List installed packages
      run: pip list